version: '3.0'
services:
  mysql:
    image: docker.io/library/mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydata
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"
    volumes:
      - acme-wp-backend:/var/lib/mysqul
    networks:
      - acme-wp

networks:
  acme-wp: {}

volumes:
  acme-wp-backend: {}
